export const SET_USER_DATA = 'AUTH/SET_USER_DATA'

export const SET_CHECKLISTS = 'CHECKLIST/SET_CHECKLISTS'
export const SET_CURRENT_CHECKLIST = 'CHECKLIST/SET_CURRENT_CHECKLIST'
export const TOGGLE_IS_FETCHING = 'CHECKLIST/TOGGLE_IS_FETCHING'
export const TOGGLE_EDITMODE = 'CHECLIST/TOGGLE_EDITMODE'

export const SET_CURRENT_USER = 'USERS/SET_CURRENT_USER'
export const USERS_TOGGLE_EDITMODE = 'USERS_TOGGLE_EDITMODE'
export const SET_USERS = 'USERS/SET_USERS'
export const USERS_TOGGLE_IS_FETCHING = 'CHECKLIST/TOGGLE_IS_FETCHING'

export const SHOW_ALERT = 'ALERT/SHOW_ALERT'
export const HIDE_ALERT = 'ALERT/HIDE_ALERT'

export const INITIALIZED_SUCCESS = 'APP/INITIALIZED_SUCCESS'